# Project structure generator config

#path: 'structure'
path:
    output_dir: 'output'
    working_dir: 'structure'
    file_path: 'student_manage.tree' # optional if multi_file_mode is false

mode: 'dry-run' # options: normal, dry-run, verbose
multi_file_mode: true
indent: 4
read_file_extension: 'tree'

# Optional: custom variables for templates (future use)
variables:
    project_name: 'MyApp'
    author: 'Omar Faruk Sarkar'

# Comment marker for documentation (optional)
doc_separator: '##'
